name: Generate ASCII ArtWork

on: push

jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install cowsay
        run: sudo apt-get install -y cowsay  

      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

      - name: Generate ASCII ArtWork
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

      - name: Test file Exist
        run: grep -i "dragon" dragon.txt
          
      - name: List files
        run: ls

      - name: Read files
        run: cat dragon.txt
      - name: checkou t Repor Files
        run: ls -ltra